version: '3'

services:
  nginx:
    image: nginx:1.23.3
    volumes:
      - ../html:/var/www/html/
      - ./conf:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - internal
  certbot:
    depends_on:
      - nginx
    image: certbot/certbot:latest
    volumes:
      - /run/certificates:/etc/nginx/ssl/live/dandadin.eu/
      - ../html:/var/www/certbot/:rw
      - /run/certificates:/etc/letsencrypt/:rw
    command: 
      - certonly
      - --webroot 
      - --webroot-path 
      - /var/www/certbot 
      - -d 
      - dandadin.eu 
      - -m 
      - dan.simanek@seznam.cz 
      - -n 
      - --agree-tos
networks:
  internal:
    driver: bridge

