version: '3'

services:
  nginx:
    image: nginx:1.23.3
    volumes:
      - ./html:/var/www/html/:ro
      - ./conf:/etc/nginx/conf.d:ro
      - /run/certificates:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    networks:
      - internal
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./html:/var/www/html/
  composer:
    image: composer/composer
    networks:
      - internal
    ports:
      - 9001:9000
    volumes:
      - ./composer:/app
      - .:/webserver
    command: "update"
#  certbot:
#    image: certbot/certbot:latest
#    volumes:
#      - ./html:/var/www/certbot/:rw
#      - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
  internal:
    driver: bridge

